[WIP]soyoil/toppage
coins-shinkan/shinkan-web-20 pull request #3
Opened 2020-03-02 06:25 UTC by soyoil

2020-03-02 10:38 UTC, sosukesuzuki reviewed
まだ WIP になってるので、もし気づいてたら申し訳ないですがESLint には従うようにしてください！
```sh
$ npm run lint:fix
```
を実行すればだいたいは修正されると思います！
VSCode で開発をしているのであれば、ESLint 用の VSCode 拡張をインストールすることをおすすめします！

2020-03-09 03:52 UTC, soyoil commented
「記事をJSONで書けるようにする」とは言ったものの，JSONだと表とかリストとかを表現するのが難しそうな気がするので，どうしようかと悩んでいます...

2020-03-17 04:25 UTC, sosukesuzuki commented on gatsby-node.js
> +  `).then(result => {
nice promise

2020-03-17 04:35 UTC, soyoil commented on src/templates/events.js
> +          </EventMenu>
ここの部分がうまく動きません（なにも表示されない）

2020-03-17 04:38 UTC, sosukesuzuki commented on src/templates/events.js
> +          </EventMenu>
それはそうで、なぜかというと forEach は配列を返さないからです（返り値がvoid)。
map を使いましょう(map は配列を返します

2020-03-17 04:38 UTC, sosukesuzuki commented on src/templates/events.js
> +            })}
```suggestion
            {eventList.map(event => {
              return (<p>
                {event.node.frontmatter.title}
                <br />
                {event.node.frontmatter.date}
              </p>)
            })}
```

2020-03-17 05:26 UTC, soyoil commented on src/templates/events.js
> +            })}
できました．ありがとうございます．

2020-03-17 17:29 UTC, yuki-js requested changes

2020-03-17 17:29 UTC, yuki-js commented on src/layouts/EventsCard.js
> +          {event.node.frontmatter.date.padEnd(18, " ")}
タイトル名を揃えるなら`table`要素でテーブルを使うか独自の段組みをCSSで書く

2020-03-17 17:29 UTC, yuki-js commented on src/pages/index.js
> +const Heading1 = styled.div`
これは見出しではないの？

2020-03-20 11:23 UTC, soyoil commented
手動マージをしたのでclose

2020-03-20 11:23 UTC, closed without merging